import Head from "next/head";
import axios from "axios";
import { useRouter } from "next/router";
import { useState } from "react";
import styles from "../styles/Home.module.scss";
import Add from "./Add";
import Data from "./Data";
import Edit from "./Edit";
import Topbar from "./Topbar";

export default function Home({ allData, page }) {
  const [pageId, setPageId] = useState("");
  const [Id, setId] = useState("");
  const [cancel, setCancel] = useState(false);
  const router = useRouter();

  const deleteData = async (_id) => {
    await axios.delete(`http://localhost:3000/api/${_id}`);
    router.push("/");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>CRUD Synapsis</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.app}>
        <Topbar cancel={cancel} setCancel={setCancel} setPage={setPageId} />
        <div className={styles.body}>
          {pageId === "add" ? (
            <Add />
          ) : pageId === "edit" ? (
            <Edit Id={Id} />
          ) : (
            <Data
              allData={allData}
              setCancel={setCancel}
              setPage={setPageId}
              deleteData={deleteData}
              setId={setId}
              page={page}
            />
          )}
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps({ query: { page = 1 } }) {
  const res = await fetch(`http://localhost:3000/api/?page=${page}`);
  const data = await res.json();

  return {
    props: {
      allData: data.data,
      page: +page,
    },
  };
}
